<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="PS-WIN-LP-91" name="com.qtpselenium.zoho.project.testcases.LeadTest" tests="6" failures="1" timestamp="10 Jun 2019 09:12:17 GMT" time="285.761" errors="0">
  <testcase name="createLeadTest" time="6.340" classname="com.qtpselenium.zoho.project.testcases.LeadTest">
    <skipped/>
  </testcase> <!-- createLeadTest -->
  <testcase name="createLeadTest" time="79.423" classname="com.qtpselenium.zoho.project.testcases.LeadTest"/>
  <testcase name="createLeadTest" time="4.690" classname="com.qtpselenium.zoho.project.testcases.LeadTest">
    <skipped/>
  </testcase> <!-- createLeadTest -->
  <testcase name="createLeadTest" time="50.020" classname="com.qtpselenium.zoho.project.testcases.LeadTest"/>
  <testcase name="convertLeadTest" time="77.719" classname="com.qtpselenium.zoho.project.testcases.LeadTest"/>
  <testcase name="deleteLeadAccountTest" time="67.569" classname="com.qtpselenium.zoho.project.testcases.LeadTest">
    <failure type="java.lang.AssertionError" message="Could not delete the lead">
      <![CDATA[java.lang.AssertionError: Could not delete the lead
at org.testng.Assert.fail(Assert.java:96)
at com.qtpselenium.zoho.project.base.BaseTest.reportFailure(BaseTest.java:219)
at com.qtpselenium.zoho.project.testcases.LeadTest.deleteLeadAccountTest(LeadTest.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- deleteLeadAccountTest -->
</testsuite> <!-- com.qtpselenium.zoho.project.testcases.LeadTest -->
